package com.today.habit.ui.component

import com.today.habit.R

/** SF Symbols 图标注册表（图标数据来自 sfsymbols.rakibulism.space，已获授权使用） */
object SFIcons {
    val All: Map<String, Int> = mapOf(
        "airplane" to R.drawable.sf_airplane,
        "alarm" to R.drawable.sf_alarm,
        "banknote" to R.drawable.sf_banknote,
        "bicycle" to R.drawable.sf_bicycle,
        "birthday.cake" to R.drawable.sf_birthday_cake,
        "book" to R.drawable.sf_book,
        "brain.head.profile" to R.drawable.sf_brain_head_profile,
        "briefcase" to R.drawable.sf_briefcase,
        "calendar" to R.drawable.sf_calendar,
        "camera" to R.drawable.sf_camera,
        "car" to R.drawable.sf_car,
        "cart" to R.drawable.sf_cart,
        "character.book.closed" to R.drawable.sf_character_book_closed,
        "chart.bar" to R.drawable.sf_chart_bar,
        "checkmark" to R.drawable.sf_checkmark,
        "chevron.down" to R.drawable.sf_chevron_down,
        "chevron.left" to R.drawable.sf_chevron_left,
        "chevron.right" to R.drawable.sf_chevron_right,
        "chevron.left.forwardslash.chevron.right" to R.drawable.sf_chevron_left_forwardslash_chevron_right,
        "chevron.up" to R.drawable.sf_chevron_up,
        "clock" to R.drawable.sf_clock,
        "clock.arrow.circlepath" to R.drawable.sf_clock_arrow_circlepath,
        "cloud.rain" to R.drawable.sf_cloud_rain,
        "cup.and.saucer" to R.drawable.sf_cup_and_saucer,
        "drop" to R.drawable.sf_drop,
        "dumbbell" to R.drawable.sf_dumbbell,
        "figure.hiking" to R.drawable.sf_figure_hiking,
        "figure.run" to R.drawable.sf_figure_run,
        "figure.walk" to R.drawable.sf_figure_walk,
        "figure.yoga" to R.drawable.sf_figure_yoga,
        "film" to R.drawable.sf_film,
        "flame" to R.drawable.sf_flame,
        "folder" to R.drawable.sf_folder,
        "fork.knife" to R.drawable.sf_fork_knife,
        "function" to R.drawable.sf_function,
        "gamecontroller" to R.drawable.sf_gamecontroller,
        "gearshape" to R.drawable.sf_gearshape,
        "gift" to R.drawable.sf_gift,
        "globe" to R.drawable.sf_globe,
        "graduationcap" to R.drawable.sf_graduationcap,
        "guitars" to R.drawable.sf_guitars,
        "headphones" to R.drawable.sf_headphones,
        "heart" to R.drawable.sf_heart,
        "house" to R.drawable.sf_house,
        "leaf" to R.drawable.sf_leaf,
        "magnifyingglass" to R.drawable.sf_magnifyingglass,
        "moon" to R.drawable.sf_moon,
        "moon.zzz" to R.drawable.sf_moon_zzz,
        "music.note" to R.drawable.sf_music_note,
        "paintbrush" to R.drawable.sf_paintbrush,
        "paintpalette" to R.drawable.sf_paintpalette,
        "pawprint" to R.drawable.sf_pawprint,
        "pencil" to R.drawable.sf_pencil,
        "person" to R.drawable.sf_person,
        "pill" to R.drawable.sf_pill,
        "plus" to R.drawable.sf_plus,
        "scissors" to R.drawable.sf_scissors,
        "snowflake" to R.drawable.sf_snowflake,
        "sparkles" to R.drawable.sf_sparkles,
        "sportscourt" to R.drawable.sf_sportscourt,
        "square.and.arrow.up" to R.drawable.sf_square_and_arrow_up,
        "star" to R.drawable.sf_star,
        "stethoscope" to R.drawable.sf_stethoscope,
        "sun.max" to R.drawable.sf_sun_max,
        "trash" to R.drawable.sf_trash,
        "trophy" to R.drawable.sf_trophy,
        "tshirt" to R.drawable.sf_tshirt,
        "tv" to R.drawable.sf_tv,
        "wrench.and.screwdriver" to R.drawable.sf_wrench_and_screwdriver,
        "xmark" to R.drawable.sf_xmark,
    )

    /** 图标选择页分类（分类名 -> 图标 key 列表），key 为 SF Symbols 名称 */
    val Categories: List<Pair<String, List<String>>> = listOf(
        "运动健康" to listOf("figure.run", "figure.walk", "figure.hiking", "figure.yoga", "bicycle", "dumbbell", "heart", "leaf", "moon.zzz", "brain.head.profile", "pill", "stethoscope", "flame"),
        "饮食" to listOf("drop", "cup.and.saucer", "fork.knife", "birthday.cake", "cart"),
        "学习工作" to listOf("book", "graduationcap", "pencil", "character.book.closed", "function", "briefcase", "clock", "alarm", "calendar", "folder", "chevron.left.forwardslash.chevron.right", "globe", "banknote"),
        "生活" to listOf("house", "sun.max", "person", "pawprint", "tshirt", "wrench.and.screwdriver", "scissors", "sparkles", "cloud.rain", "snowflake"),
        "休闲娱乐" to listOf("music.note", "guitars", "headphones", "paintpalette", "paintbrush", "film", "tv", "gamecontroller", "sportscourt", "camera", "trophy", "star", "gift", "airplane", "car"),
    )

    /** 图标 key -> 中文名称（用于搜索与无障碍描述） */
    val Labels: Map<String, String> = mapOf(
        "airplane" to "旅行",
        "alarm" to "闹钟",
        "banknote" to "理财",
        "bicycle" to "骑行",
        "birthday.cake" to "生日",
        "book" to "阅读",
        "brain.head.profile" to "冥想",
        "briefcase" to "工作",
        "calendar" to "日程",
        "camera" to "摄影",
        "car" to "自驾",
        "cart" to "购物",
        "character.book.closed" to "学习",
        "chart.bar" to "统计",
        "checkmark" to "完成",
        "chevron.down" to "收起",
        "chevron.left" to "返回",
        "chevron.left.forwardslash.chevron.right" to "编程",
        "chevron.up" to "展开",
        "clock" to "时间",
        "clock.arrow.circlepath" to "恢复",
        "cloud.rain" to "天气",
        "cup.and.saucer" to "咖啡",
        "drop" to "喝水",
        "dumbbell" to "健身",
        "figure.hiking" to "登山",
        "figure.run" to "跑步",
        "figure.walk" to "散步",
        "figure.yoga" to "瑜伽",
        "film" to "电影",
        "flame" to "活力",
        "folder" to "整理",
        "fork.knife" to "饮食",
        "function" to "数学",
        "gamecontroller" to "游戏",
        "gearshape" to "设置",
        "gift" to "礼物",
        "globe" to "外语",
        "graduationcap" to "毕业",
        "guitars" to "吉他",
        "headphones" to "播客",
        "heart" to "心率",
        "house" to "居家",
        "leaf" to "自然",
        "magnifyingglass" to "搜索",
        "moon" to "夜间",
        "moon.zzz" to "睡眠",
        "music.note" to "音乐",
        "paintbrush" to "涂鸦",
        "paintpalette" to "绘画",
        "pawprint" to "宠物",
        "pencil" to "记录",
        "person" to "个人",
        "pill" to "用药",
        "plus" to "添加",
        "scissors" to "手工",
        "snowflake" to "冬季",
        "sparkles" to "打扫",
        "sportscourt" to "运动",
        "square.and.arrow.up" to "备份",
        "star" to "星标",
        "stethoscope" to "健康",
        "sun.max" to "早起",
        "trash" to "删除",
        "trophy" to "目标",
        "tshirt" to "穿搭",
        "tv" to "追剧",
        "wrench.and.screwdriver" to "维修",
        "xmark" to "关闭",
    )

    fun res(key: String): Int = All[key] ?: R.drawable.sf_sun_max
    fun label(key: String): String = Labels[key] ?: key
}
